### ISSUE TITLE
How to run and test against my Rp?

### ISSUE THREAD

**Issue by afridi26** [bodik/soft-webauthn#3]
Hi, thanks for such a nice start. I am curious and not able to run this project for my RP. Can you please provide a short note on how to run and test it?

**Comment by bodik** [comment]
hi, thanks for feedback. I'm not sure what exactly are you missing ...

The example code can be found in `tests/test_example.py`  and it is noted in README.md.

I might think that the problem here, is that there's no spec for RP itself so one cannot directly write a generic test/code to test any arbitrary RP out of the box. Is this what's missing in readme ?

**Comment by bodik** [comment]
I've tried to do my best to rephrase the purpose and usage ...

https://github.com/bodik/soft-webauthn/blob/dev-better_docs/README.md

does it look better ?

**Comment by bodik** [comment]
released better documentation as new version (because of pypi upload)
